#!/usr/bin/env python3
"""Regenerate references/catalog.md from the actual contents: effects (fx_pack), templates (mg), sounds and music beds."""
import os, subprocess, sys
HERE = os.path.dirname(os.path.abspath(__file__)); sys.path.insert(0, HERE)
import fx_pack, mg  # noqa: E402
from assets_path import SFX_DIR, MUSIC_DIR  # noqa: E402

ROOT = os.path.join(HERE, ".."); SFX, MUS = SFX_DIR, MUSIC_DIR
CATS = [  # first matching keyword wins
    ("Whooshes, swishes & transitions", ["whoosh", "swish", "swoosh", "swipe", "sweep", "spin", "flutter"]),
    ("Impacts, hits, booms & stingers", ["impact", "hit", "boom", "stinger", "braam", "gong", "bell_toll", "tail", "sub_drop", "brass", "vine"]),
    ("Risers, builds & downlifters", ["riser", "uplifter", "downlifter", "tension", "drone", "reverse", "cymbal_swell", "shimmer", "charge", "snare_roll", "countdown"]),
    ("Drums & percussion", ["kick", "snare", "clap", "hihat", "tom", "rimshot", "crash", "ride", "drum", "darbuka", "tabla", "cowbell", "ba_dum"]),
    ("Engine & mechanical", ["engine"]),
    ("UI, interface & social", ["pop", "click", "tick", "tap", "toggle", "ui_", "confirm", "cancel", "notification", "message", "typing", "keyboard", "send", "like", "scroll", "camera", "ding", "chime", "error_buzz", "success"]),
    ("Cartoon & fun", ["boing", "slide_whistle", "bonk", "squeak", "cork", "bubble", "splat", "spring", "wobble", "cartoon"]),
    ("Game / 8-bit", ["blip", "jump", "coin", "power_", "level", "game_over", "laser", "explosion", "select", "8bit", "pickup"]),
    ("Sci-fi, glitch & tech", ["glitch", "digital", "warp", "teleport", "hologram", "scanner", "sonar", "radio", "tape", "vinyl_stop", "vhs", "dial", "zap", "data", "alarm", "siren", "record_scratch"]),
    ("Real-world foley (synthetic)", ["whip", "punch", "slap", "sword", "glass", "water", "splash", "thunder", "wind", "fire", "rain", "door", "cash", "footstep", "paper", "zipper", "pour", "wood", "balloon", "clock", "stopwatch", "heartbeat", "vinyl_crackle", "stopwatch"]),
    ("Comedy, meme & emotion", ["sad_", "airhorn", "dun_", "crickets", "tada", "fail", "applause", "wow", "awkward", "bruh", "ding_dong", "magic", "sparkle", "fanfare"]),
]
def cat(n):
    for c, ks in CATS:
        if any(k in n for k in ks): return c
    return "Other"
def dur(p): return float(subprocess.run(["ffprobe", "-v", "error", "-show_entries", "format=duration", "-of", "csv=p=0", p], capture_output=True, text=True).stdout)

out = ["# Catalog (generated by scripts/make_catalog.py)\n", "Everything here ships with the skill. Names are what you pass to `sfx-mix`, the plan JSON, or the CLI.\n"]
sfx = sorted(f[:-4] for f in os.listdir(SFX) if f.endswith(".mp3")); groups = {}
for n in sfx: groups.setdefault(cat(n), []).append(n)
out.append(f"## Sound effects ({len(sfx)})\nPeak-normalised to -3 dB; set loudness per cue with the gain value. Durations in seconds.\n")
for c, _ in CATS + [("Other", [])]:
    if c in groups: out.append(f"**{c}** ({len(groups[c])}): " + ", ".join(f"`{n}` {dur(os.path.join(SFX, n + '.mp3')):.1f}s" for n in groups[c]) + "\n")
beds = sorted(f[:-4] for f in os.listdir(MUS) if f.endswith(".mp3"))
out.append(f"## Music beds ({len(beds)}, loopable, synthesised)\nUse as `\"music\": {{\"file\": \"NAME\", \"db\": -14}}` in a plan, or `reel_tools.py mix-music`. They duck under speech/SFX.\n")
out += [f"- `{b}` ({dur(os.path.join(MUS, b + '.mp3')):.0f}s)" for b in beds]
out.append(f"\n## Video effects ({len(fx_pack.REG)}) - `python scripts/fx_pack.py NAME IN OUT [--at S:E] [--p k=v]`\n")
out.append("| Effect | What it does | Params (defaults) |\n|---|---|---|")
for k, v in sorted(fx_pack.REG.items()):
    out.append(f"| `{k}` | {v['doc']} | {', '.join(f'{a}={b}' for a, b in v['defaults'].items()) or '-'} |")
out.append(f"\n## Motion-graphic templates ({len(mg.REG)}) - `python scripts/mg.py TEMPLATE OUT.mov --p k=v`\n")
out.append("| Template | What it does | Params (defaults), duration |\n|---|---|---|")
for k, v in mg.REG.items():
    out.append(f"| `{k}` | {v['doc']} | {', '.join(f'{a}={b!r}' for a, b in v['defaults'].items())}; {v['dur']}s |")
out.append(f"\n## Transitions ({len(__import__('pro_fx').XFADES)}) - `pro_fx.py transition OUT a.mp4 b.mp4 --kind NAME[,NAME2] --dur 0.4`\n")
out.append(", ".join(f"`{x}`" for x in __import__("pro_fx").XFADES))
out.append("\n## Looks (`pro_fx.py grade --look`)\n" + ", ".join(f"`{k}`" for k in __import__("pro_fx").LOOKS))
out.append("\n## Caption styles (`pro_fx.py animated-subs --style`)\n" + ", ".join(f"`{k}`" for k in __import__("pro_fx").STYLES))
open(os.path.join(ROOT, "references", "catalog.md"), "w", encoding="utf-8").write("\n".join(out) + "\n")
print("wrote references/catalog.md:", len(sfx), "sfx,", len(beds), "beds,", len(fx_pack.REG), "effects,", len(mg.REG), "templates")
